# Chapter 10 - Risk & Returns

Corporate Finance 9th International Edition

Ross, Westerfield, Jaffe

# Financial Calculator

In [1]:
import pandas as pd
import numpy as np
import numpy_financial as npf
from IPython.display import display, HTML

# Formulas

In [2]:
"""
Dividend Yield = Div_t+1
                 ---------
                    Pt

Capital Gain = (P_t+1 - Pt)
               ------------
                    Pt

Total Return =    Div_t+1     ( P_t+1 - Pt )      
                 --------- +  --------------
                    Pt            Pt  

Arithmetic Mean = R_hat = ( R1 + ... + Rt )
                          -----------------
                                  T
                                  
Geometric Mean = [(1 + R1) x (1 + R2) x ... x (1 + RT)]^1/T - 1

Difference between the Arithmetic & Geometric Mean:  The Geometric mean tells you 
what you actually earned per year, on average, compounded annually.  The Arithmetic Mean
tells you what you earned in a typical year an is an unbiased estimate of the true mean 
of the distribution.

The Geometric Mean is very useful in describing the actual historical investment experience.
The Arithmetic Mean is useful in making estimates of the future.

Variance =   1
           ----- [(R1 - R_hat)^2 + (R2 - R_hat)^2 + ... (RT - R_hat)^2] 
           T - 1

Standard Deviation (SD) = sqrt(Variance)

Standard Error (SE) =          SD(R)
                      ------------------------
                       sqrt(# of observations)

The Standard Error helps with the issue of how much confidence we can have in our historical
average.

Sharpe Ratio =   Average Equity Risk Premium
               -------------------------------
                 Stdev of Equity Risk Premium
"""

'\nDividend Yield = Div_t+1\n                 ---------\n                    Pt\n\nCapital Gain = (P_t+1 - Pt)\n               ------------\n                    Pt\n\nTotal Return =    Div_t+1     ( P_t+1 - Pt )      \n                 --------- +  --------------\n                    Pt            Pt  \n\nArithmetic Mean = R_hat = ( R1 + ... + Rt )\n                          -----------------\n                                  T\n\nGeometric Mean = [(1 + R1) x (1 + R2) x ... x (1 + RT)]^1/T - 1\n\nDifference between the Arithmetic & Geometric Mean:  The Geometric mean tells you \nwhat you actually earned per year, on average, compounded annually.  The Arithmetic Mean\ntells you what you earned in a typical year an is an unbiased estimate of the true mean \nof the distribution.\n\nThe Geometric Mean is very useful in describing the actual historical investment experience.\nThe Arithmetic Mean is useful in making estimates of the future.\n\nVariance =   1\n           ----- [(R1 - R_hat)^2 + (R2 - R_hat)^2 + ... (RT - R_hat)^2] \n           T - 1\n\nStandard Deviation (SD) = sqrt(Variance)\n\nStandard Error (SE) =          SD(R)\n                      ------------------------\n                       sqrt(# of observations)\n\nThe Standard Error helps with the issue of how much confidence we can have in our historical\naverage.\n\nSharpe Ratio =   Average Equity Risk Premium\n               -------------------------------\n                 Stdev of Equity Risk Premium\n'

# Dataset

In [3]:
# We will need this data later.
csv_file = "./../datasets/total_returns_1926-2008.csv"
total_returns = pd.read_csv(csv_file)
total_returns.head()

,Year,Large-Company Stock,Long-Term Government Bonds,U.S. Treasury Bills,Consumer Price Index
0,1926,11.14,7.90,3.30,-1.12
1,1927,37.13,10.36,3.15,-2.26
2,1928,43.31,-1.37,4.05,-1.16
3,1929,-8.91,5.23,4.47,0.58
4,1930,-25.26,5.80,2.27,-6.40

# Problems

**1. Calculating Returns**

Suppose a stock had an initial price of 92 per share, paid a dividend of 1.45 per share during the year, and had an ending share price of 104.  **Compute the Percentage Total Return.**

In [4]:
initial_price = 92
dividend = 1.45
ending_price = 104

Percentage_Total_Return = (dividend / initial_price) + ((ending_price - initial_price) / initial_price)
ptr = f'Percentage Total Return: {Percentage_Total_Return*100:.2f}%'
ptr

'Percentage Total Return: 14.62%'

**2. Calculating Yields**

In Problem 1, what was the dividend yield? The Capital Gains Yield?

In [5]:
dividend_yield = (dividend / initial_price)
capital_gains_yield = ((ending_price - initial_price) / initial_price)

div_yield = f'Dividend Yield: {dividend_yield*100:.2f}%'  
cap_yield = f'Capital Gains Yield: {capital_gains_yield*100:.2f}%'

print(f'{div_yield}\n{cap_yield}')

Dividend Yield: 1.58%
Capital Gains Yield: 13.04%

**3. Calculating Returns**

Rework Problems 1 and 2 assuming the ending share price is 81.

In [6]:
ending_price = 81

Percentage_Total_Return = (dividend / initial_price) + ((ending_price - initial_price) / initial_price)
print(f'Percentage Total Return: {Percentage_Total_Return*100:.2f}%')

dividend_yield = (dividend / initial_price)
capital_gains_yield = ((ending_price - initial_price) / initial_price)

div_yield = f'Dividend Yield: {dividend_yield*100:.2f}%'  
cap_yield = f'Capital Gains Yield: {capital_gains_yield*100:.2f}%'

print(f'{div_yield}\n{cap_yield}')

Percentage Total Return: -10.38%
Dividend Yield: 1.58%
Capital Gains Yield: -11.96%

**4. Calculating Returns**

Suppose you bought an 8 percent coupon bond one year ago for 1,090.  The bond sells for 1,056 today.

1. Assuming a 1,000 face value, what was your toal dollar return on this investment over the past year?
2. What was your total nominal rate of return on this investment over the past year
3. If the inflation rate last year was 3 percent, what was your total real rate of return on this investment?

In [7]:
beginning_price = 1090
ending_price = 1056
coupon = .08

# 1. Total Dollar Return
face = 1000
total_dollar_return = (ending_price - beginning_price) + (face * coupon)
print(f'Total Dollar Return on Investment: ${total_dollar_return:.2f}')

# 2. Nominal Rate of Return
nominal_rate_of_return = ((ending_price - beginning_price) + (face * coupon)) / beginning_price
print(f'Nominal Rate of Return: {nominal_rate_of_return*100:.2f}%')

# 3. Total Real Rate of Return
inflation = .03
real_rate = (1 + nominal_rate_of_return)/(1 + inflation) - 1 # Fisher effect
print(f'Real Rate of Return: {real_rate*100:.2f}%')

Total Dollar Return on Investment: $46.00
Nominal Rate of Return: 4.22%
Real Rate of Return: 1.18%

**5. Nominal versus Real Returns**

What was the arithmetic average annual return on large-company stocks from 1926 through 2008:

1. In nominal terms?
2. In real terms?

In [8]:
inflation = total_returns["Consumer Price Index"].mean() / 100
nominal_terms = total_returns["Large-Company Stock"].mean() / 100
real_terms = (1 + nominal_terms)/(1 + inflation) - 1 # Fisher effect
print(f"Nominal terms: {nominal_terms*100:.2f}%\nReal terms: {real_terms*100:.2f}%")

Nominal terms: 11.54%
Real terms: 8.19%

**6. Bond Returns**

What is the historical real return on: 
1. Long-term government bonds?
2. Long-term corporate bonds?

In [9]:
# inflation
inflation = total_returns["Consumer Price Index"].mean() / 100

# Long-term government bonds
government_bonds = total_returns["Long-Term Government Bonds"].mean() / 100
real_government_bonds = (1 + government_bonds) / (1 + inflation) - 1 # Fisher effect

# Long-term corporate bonds
# Rate of 6.2 obtained from Table 10.3, Page 317, Corporate Finance 9th
corporate_bonds = 6.2 / 100 
real_corporate_bonds = (1 + corporate_bonds) / (1 + inflation) - 1 # Fisher effect

print(f"Long-term Government Bonds: {real_government_bonds*100:.2f}%")
print(f"Long-term Corporate Bonds: {real_corporate_bonds*100:.2f}%")

Long-term Government Bonds: 2.82%
Long-term Corporate Bonds: 3.01%

**7. Calculating Returns & Variability** 

Using the following returns, calculate the average returns, the variances, and the standard deviations for X and Y:

In [10]:
"""
Year      X       Y
----     ---     ---
 1       15%     18%
 2       23      29
 3      -34     -31
 4       16      19
 5        9      11
----     ---    ---
"""

'\nYear      X       Y\n----     ---     ---\n 1       15%     18%\n 2       23      29\n 3      -34     -31\n 4       16      19\n 5        9      11\n----     ---    ---\n'

In [11]:
# Easier if we just group our data in a dataframe
df = pd.DataFrame([[1, .15, .18],
                   [2, .23, .29],
                   [3, -.34, -.31],
                   [4, .16, .19],
                   [5, .09, .11]],
                 columns=("Year", "X", "Y")
)

average_row = pd.DataFrame({
    "Year": ["Mean"],
    "X": [df["X"].mean()],
    "Y": [df["Y"].mean()]
})

variance_row = pd.DataFrame({
    "Year": ["Variance"],
    "X": [np.var(df["X"], ddof=1)],
    "Y": [np.var(df["Y"], ddof=1)]
})

stdev_row = pd.DataFrame({
    "Year": ["StDev"],
    "X": [np.std(df["X"], ddof=1)],
    "Y": [np.std(df["Y"], ddof=1)]
})

df = pd.concat([df, average_row, variance_row, stdev_row], ignore_index=True)

# Convert returns to percentages
df['X'] = df['X'].apply(lambda x: x * 100 if isinstance(x, (int, float)) else x)
df['Y'] = df['Y'].apply(lambda x: x * 100 if isinstance(x, (int, float)) else x)

# Format the values to two decimal places
df['X'] = df['X'].apply(lambda x: f"{x:.2f}%" if isinstance(x, (int, float)) else x)
df['Y'] = df['Y'].apply(lambda x: f"{x:.2f}%" if isinstance(x, (int, float)) else x)

display(HTML(df.to_html(index=False)))

**8. Risk Premium**

Refer to Table 10.1 (total_returns) in the text and look athe period from 1973 through 1978.
1. Calculate the arithmetic average returns for large-company stocks and T-Bills over the period.
2. Calculate the standardard deviation of the retuns for large-company stocks and T-Bills over the period.
3. Calculate the observed risk premium in each year for the large-company stocks versus T-Bills.  What was the the arithmetic average risk premium over this period? What was the standard deviation of the risk premium over this period?

In [12]:
# We can answer all this question in one dataframe

start_year = 1973
end_year = 1978

variables = ["Year", "Large-Company Stock", "U.S. Treasury Bills"]
sample = total_returns[variables]
sample = sample[(sample["Year"] >= start_year) & (sample["Year"] <= end_year)         ]
sample["Risk Premium"] = sample["Large-Company Stock"] - sample["U.S. Treasury Bills"]

average_row = pd.DataFrame({
    "Year": ["Mean"],
    "Large-Company Stock": [sample["Large-Company Stock"].mean()],
    "U.S. Treasury Bills": [sample["U.S. Treasury Bills"].mean()],
    "Risk Premium": [sample["Risk Premium"].mean()]
})

stdev_row = pd.DataFrame({
    "Year": ["StDev"],
    "Large-Company Stock": [np.std(sample["Large-Company Stock"], ddof=1)],
    "U.S. Treasury Bills": [np.std(sample["U.S. Treasury Bills"], ddof=1)],
    "Risk Premium": [np.std(sample["Risk Premium"], ddof=1)],
})

sample = pd.concat([sample, average_row, stdev_row], ignore_index=True)

# Format the values to two decimal places
sample['Large-Company Stock'] = sample['Large-Company Stock'].apply(lambda x: f"{x:.2f}%" if isinstance(x, (int, float)) else x)
sample['U.S. Treasury Bills'] = sample['U.S. Treasury Bills'].apply(lambda x: f"{x:.2f}%" if isinstance(x, (int, float)) else x)
sample['Risk Premium'] = sample['Risk Premium'].apply(lambda x: f"{x:.2f}%" if isinstance(x, (int, float)) else x)

display(HTML(sample.to_html(index=False)))

**9. Calculating Returns and Variability**

You've observed the following returns on Mary Ann Data Corporation's stock over the past five years:

1.  34%
2.  16%
3.  19%
4. -21%
5.   8%

Questions:
1. What was the arithmetic average return on Mary Ann's stock over the five-year period?
2. What was the variance of Mary Ann's returns over this period? The Standard Deviation?

In [13]:
returns = pd.DataFrame([["1", .34],
                        ["2", .16], 
                        ["3", .19], 
                        ["4", -.21], 
                        ["5", .08]],
                      columns=("Year", "Returns"))

average_row = pd.DataFrame({
    "Year": ["Mean"],
    "Returns": [returns["Returns"].mean()]
})

variance_row = pd.DataFrame({
    "Year": ["Variance"],
    "Returns": [np.var(returns["Returns"], ddof=1)]
})

stdev_row = pd.DataFrame({
    "Year": ["StDev"],
    "Returns": [np.std(returns["Returns"], ddof=1)]
})

returns = pd.concat([returns, average_row, variance_row, stdev_row], ignore_index=True)

# Convert returns to percentages
returns['Returns'] = returns['Returns'].apply(lambda x: x * 100 if isinstance(x, (int, float)) else x)

# Format the values to two decimal places
returns['Returns'] = returns['Returns'].apply(lambda x: f"{x:.2f}%" if isinstance(x, (int, float)) else x)

display(HTML(returns.to_html(index=False)))

**10. Calculating Real Returns and Risk Premiums**

In Problem 9, suppose the average inflation rate over this period was 4.2 percent, and the average T-bill rate over the period was 5.1 percent:

1. What was the the average real return on Mary Ann's stock?
2. What was the average nominal risk premium on Mary Ann's stock?

In [15]:
# 1 - Average Real Return
inflation = .042
avg_return = .1120 # From Problem 9.
avg_real_return = (1 + avg_return) / (1 + inflation) - 1 # Fisher effect
print(f"Average Real Return: {avg_real_return*100:.2f}%")

# 2 - Average Nominal Risk Premium
average_tbill = .051
avg_nominal_risk_premium = avg_return - average_tbill
print(f"Average Nominal Risk Premium: {avg_nominal_risk_premium*100:.2f}%")

Average Real Return: 6.72%
Average Nominal Risk Premium: 6.10%

**11. Calculating Real Rates**

Given the information Problem 10: 
1. What was the average real risk-free rate over over this time period?
2. What was the average real risk premium?

In [22]:
# 1 - Average Real  Risk-Free Premium
avg_real_risk_free_premium = (1 + average_tbill) / (1 + inflation) - 1 # Fisher Effect
print(f"Average Real Risk-Free Rate: {avg_real_risk_free_premium*100:.2f}%")

# 2 - Average Real Risk premium
avg_real_risk_premium = avg_nominal_risk_premium - avg_real_risk_free_premium
print(f"Average Real Risk Premium: {avg_real_risk_premium*100:.2f}%")

Average Real Risk-Free Rate: 0.86%
Average Real Risk Premium: 5.24%